/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Button, Flex, Text} from "@aws-amplify/ui-react";
export default function MarketingFooter(props) {
  const { overrides, ...rest } = props;
  return (
    <Flex
      gap="32px"
      direction="column"
      width="100%"
      height="600px"
      justifyContent="flex-start"
      alignItems="center"
      position="relative"
      padding="1.5% 10% 1.5% 10%"
      backgroundColor="rgba(128,0,64,1)"
      {...getOverrideProps(overrides, "MarketingFooter")}
      {...rest}
    >

      <Flex
        gap="1%"
        direction="row"
        width="unset"
        height="100%"
        justifyContent="flex-start"
        alignItems="flex-start"
        shrink="0"
        alignSelf="stretch"
        position="center"
        padding="36px 36px 36px 36px"
        backgroundColor="rgba(255,255,255,1)"
        borderRadius="35px"
        {...getOverrideProps(overrides, "Frame 40529766988")}
      >
        <Flex
          gap="8px"
          direction="column"
          width="25%"
          height="25%"
          justifyContent="flex-start"
          alignItems="flex-start"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Frame 403")}
        >
          <Text
            fontFamily="Inter"
            fontSize="22px"
            fontWeight="600"
            color="black"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Acerca"
            {...getOverrideProps(overrides, "Products")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Mision"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Vision"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          
        </Flex>
        <Flex
          gap="8px"
          direction="column"
          width="25%"
          height="25%"
          justifyContent="flex-start"
          alignItems="flex-start"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Frame 403")}
        >
          <Text
            fontFamily="Inter"
            fontSize="22px"
            fontWeight="600"
            color="black"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Servicios"
            {...getOverrideProps(overrides, "Products")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Capacitación"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Uso de instalaciones"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Impresión 3D"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Soluciones Especializadas Tecnologicas"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Desarrollo de proyectos"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>

          
        </Flex>
        <Flex
          gap="8px"
          direction="column"
          width="25%"
          height="25%"
          justifyContent="flex-start"
          alignItems="flex-start"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Frame 403")}
        >
          <Text
            fontFamily="Inter"
            fontSize="22px"
            fontWeight="600"
            color="black"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Certificaciones"
            {...getOverrideProps(overrides, "Products")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Diseño Profesional"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Diseño Básico"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Green Belt"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Yellow Belt"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="NOM ECO680"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          
        </Flex>
        <Flex
          gap="8px"
          direction="column"
          width="25%"
          height="25%"
          justifyContent="flex-start"
          alignItems="flex-start"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Frame 403")}
        >
          <Text
            fontFamily="Inter"
            fontSize="22px"
            fontWeight="600"
            color="black"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Contacto"
            {...getOverrideProps(overrides, "Products")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Directorio"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="19px"
            fontWeight="400"
            color="rgba(128,0,64,1)"
            textDecoration="underline"
            lineHeight="24px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            letterSpacing="0.01px"
            width="200px"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="+52 618 366 4848"
            {...getOverrideProps(overrides, "Libraries")}
          ></Text>
          
        </Flex>
        
      </Flex>

    </Flex>
  );
}
